// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eclmgkajlhrstyyhejev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbG1na2FqbGhyc3R5eWhlamV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODgzNDAsImV4cCI6MjA3MjI2NDM0MH0.fvA7SpoofVp3iBqc4uYfQX49rp1MooLWfHC3uFM7-Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});